title: Your awesome title
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/S-matic" # the subpath of your site, e.g. /blog
url: "https://garib2.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
remote_theme: "pages-themes/minimal@v0.2.0"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-toc
toc:
  min_level: 1
  max_level: 3
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 1..6
  input: GFM
  math_engine: mathjax
  mathjax:
    path: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
